"""
db/models.py — SQLAlchemy ORM models

WHY THIS FILE EXISTS:
    This is the schema of EvalForge's PostgreSQL database expressed in Python.
    SQLAlchemy maps each class to a table; Alembic reads these classes to
    generate migration SQL.

    RELATIONSHIP TO OTHER FILES:
    ┌─ db/models.py ──────────────────────────────────────────────────────────┐
    │  Defines: Target, EvalJob, TestCase, Result                             │
    │  Used by:                                                               │
    │    memory/store.py        ← reads/writes rows                          │
    │    agents/memory_agent.py ← calls store.py                             │
    │    api/routers/targets.py ← reads Target rows                          │
    │    api/routers/jobs.py    ← reads/writes EvalJob rows                  │
    │    db/migrations/         ← Alembic auto-generates SQL from these       │
    └─────────────────────────────────────────────────────────────────────────┘

    TABLE DESIGN RATIONALE:
    - targets        : system under test — registered once, evaluated many times
    - eval_jobs      : one run of the full eval pipeline (one entry per `POST /jobs`)
    - test_cases     : the individual questions generated by TestGen for that job
    - results        : one row per (job × test_case) — the raw response + scores

    The JSONB `config` column on targets and `report` column on eval_jobs let us
    store semi-structured data without additional tables.  JSONB is indexable in
    PostgreSQL so we can still query inside it efficiently.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    """All models inherit from this.  Alembic uses Base.metadata to discover tables."""
    pass


class JobStatus(str, enum.Enum):
    """
    Lifecycle of an eval job.

    queued        → ARQ worker has not picked it up yet
    running       → LangGraph is executing nodes
    hitl_pending  → Graph paused at hitl_gate node; waiting for human /approve
    complete      → Report generated and stored
    failed        → Unrecoverable error; see eval_jobs.error_message
    """
    QUEUED = "queued"
    RUNNING = "running"
    HITL_PENDING = "hitl_pending"
    COMPLETE = "complete"
    FAILED = "failed"


class Target(Base):
    """
    A system under evaluation.

    Examples:
      - Your RAG Stock Analyzer (http://localhost:8001/query)
      - A deployed chatbot (https://myapp.com/api/chat)
      - EvalForge itself (self-eval via eval_self.yml)

    The `config` JSONB column stores the full TargetConfig dict so we can
    reconstruct the TargetConfig Pydantic model without extra columns.
    """
    __tablename__ = "targets"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(255), nullable=False)
    endpoint = Column(Text, nullable=False)
    config = Column(JSONB, default=dict)          # Full TargetConfig serialised
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # One target → many eval jobs (one per run)
    jobs = relationship("EvalJob", back_populates="target", lazy="selectin")


class EvalJob(Base):
    """
    One complete eval run.

    Created when a user POSTs to /api/v1/jobs.
    Status transitions: queued → running → [hitl_pending →] complete | failed.

    The `report` JSONB column stores the final EvalReport model as JSON.
    We store it denormalised here so GET /api/v1/jobs/{id} is a single query.
    """
    __tablename__ = "eval_jobs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    target_id = Column(UUID(as_uuid=True), ForeignKey("targets.id"), nullable=False)
    status = Column(
        Enum(JobStatus, name="job_status_enum"),
        default=JobStatus.QUEUED,
        nullable=False,
    )
    triggered_by = Column(String(255))             # user email / "ci" / "schedule"
    started_at = Column(DateTime(timezone=True))
    completed_at = Column(DateTime(timezone=True))
    error_message = Column(Text)
    report = Column(JSONB)                         # EvalReport model as JSON

    target = relationship("Target", back_populates="jobs")
    test_cases = relationship("TestCase", back_populates="job", lazy="selectin")
    results = relationship("Result", back_populates="job")


class TestCase(Base):
    """
    One question generated by TestGen for this job.

    WHY STORED IN DB:
      - Memory Agent queries past test cases to detect regression patterns
      - "Test case X failed in run #3, passed in run #4, failed in run #7" —
        that flapping detection requires matching test cases across runs by ID
      - User-defined test cases persist here so they re-run automatically
    """
    __tablename__ = "test_cases"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(UUID(as_uuid=True), ForeignKey("eval_jobs.id"), nullable=False)
    question = Column(Text, nullable=False)
    category = Column(String(64), nullable=False)  # TestCategory enum value
    expected_behavior = Column(Text)
    ground_truth = Column(Text)
    tags = Column(ARRAY(String))                   # ["rag", "finance", ...]
    source = Column(String(32), default="generated")  # "generated"|"regression"|"user_defined"

    job = relationship("EvalJob", back_populates="test_cases")
    result = relationship("Result", back_populates="test_case", uselist=False)


class Result(Base):
    """
    Raw response + scores for one (job, test_case) pair.

    WHY SEPARATE FROM test_cases:
      A test case can be re-run across multiple jobs (regression detection).
      Keeping results separate lets us query "all scores for test_case_id X
      across all jobs" to find flapping failures.

    scored_by values:
      "lora"      → Fast local classifier only (Phase 4, once LoRA is trained)
      "llm_judge" → Ollama gemma4:26b judge (used now, in Phase 1)
      "hybrid"    → LoRA flagged low confidence; LLM judge used as fallback
    """
    __tablename__ = "results"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    test_case_id = Column(UUID(as_uuid=True), ForeignKey("test_cases.id"), nullable=False)
    job_id = Column(UUID(as_uuid=True), ForeignKey("eval_jobs.id"), nullable=False)
    response_text = Column(Text)
    latency_ms = Column(Integer)

    # Scores (0.0 – 1.0)
    factual_consistency = Column(Float)
    relevance = Column(Float)
    completeness = Column(Float)
    safety = Column(Float, default=1.0)
    hallucination_detected = Column(Boolean, default=False)

    judge_reasoning = Column(Text)
    scored_by = Column(String(32), default="llm_judge")
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    job = relationship("EvalJob", back_populates="results")
    test_case = relationship("TestCase", back_populates="result")
