"""
api/schemas/job.py — Eval job & test-case schemas

WHY THIS FILE EXISTS:
    Defines all the intermediate data shapes that flow through the LangGraph
    pipeline.  These are the types that agents pass between each other via
    EvalState (defined in agents/orchestrator.py).

    RELATIONSHIP TO OTHER FILES:
    ┌─ api/schemas/job.py ────────────────────────────────────────────────────┐
    │  TestCase      → produced by testgen_agent, consumed by execution_agent │
    │  Result        → produced by execution_agent, consumed by judge_agent   │
    │  Score         → produced by judge_agent, consumed by memory/report     │
    │  JobCreate     → API request body for POST /api/v1/jobs                │
    │  JobRead       → API response for GET /api/v1/jobs/{id}                │
    │  All models are imported into agents/orchestrator.py::EvalState        │
    └─────────────────────────────────────────────────────────────────────────┘
"""

from enum import Enum
from typing import Literal, Optional
from uuid import UUID, uuid4
from datetime import datetime

from pydantic import BaseModel, Field


class TestCategory(str, Enum):
    """
    Categories of test cases generated by TestGen.

    WHY CATEGORIES MATTER:
    The Report Agent uses category breakdown to tell you *where* your LLM
    system is weak, not just that it failed.  "78% hallucination rate on
    hallucination_trap questions" is far more actionable than "overall score: 62".
    """
    FACTUAL_PROBE = "factual_probe"        # Known ground-truth answer exists
    ADVERSARIAL = "adversarial"            # Prompt injection / jailbreak attempts
    HALLUCINATION_TRAP = "hallucination_trap"  # Questions about things that don't exist
    CONTEXT_BOUNDARY = "context_boundary"  # Edge of the system's knowledge
    REGRESSION = "regression"              # Previously failing cases re-run
    MULTI_HOP = "multi_hop"               # Multi-step reasoning required


class TestCase(BaseModel):
    """
    A single question to send to the target system.

    id is pre-assigned (UUID) so it can be stored in the DB before execution
    and referenced by the Result without a second DB round-trip.
    """
    id: str = Field(default_factory=lambda: str(uuid4()))
    question: str
    category: TestCategory
    expected_behavior: str = Field(
        ...,
        description="Behavioral expectation — not an exact answer.  "
                    "E.g. 'Should refuse to answer and explain why.'",
    )
    ground_truth: Optional[str] = None     # Only set for factual_probe cases
    tags: list[str] = Field(default_factory=list)
    source: Literal["generated", "regression", "user_defined"] = "generated"


class Result(BaseModel):
    """
    Raw output from the target system for one test case.

    Produced by execution_agent; consumed by judge_agent.
    latency_ms is tracked so the Report can surface p95 latency issues.
    """
    test_case_id: str
    response_text: str
    latency_ms: int
    status: Literal["success", "timeout", "error"] = "success"
    error_detail: Optional[str] = None     # populated on timeout/error


class Score(BaseModel):
    """
    Judge Agent's assessment of one (question, response) pair.

    scored_by tracks which scoring path was used:
      "llm_judge" → Ollama gemma4:26b (current Phase 1 default)
      "lora"      → Fine-tuned DeBERTa classifier (Phase 4)
      "hybrid"    → LoRA classified but confidence was low; LLM judge used
    """
    test_case_id: str
    factual_consistency: float = Field(ge=0.0, le=1.0)
    relevance: float = Field(ge=0.0, le=1.0)
    completeness: float = Field(ge=0.0, le=1.0)
    safety: float = Field(ge=0.0, le=1.0, default=1.0)
    hallucination_detected: bool = False
    judge_reasoning: Optional[str] = None
    scored_by: Literal["lora", "llm_judge", "hybrid"] = "llm_judge"


class JobCreate(BaseModel):
    """Request body for POST /api/v1/jobs"""
    target_id: UUID
    triggered_by: str = "api"
    seed_questions: Optional[list[str]] = None   # Optional extra questions for TestGen
    num_test_cases: int = Field(default=10, ge=1, le=50)


class JobRead(BaseModel):
    """Response body for GET /api/v1/jobs/{id}"""
    model_config = {"from_attributes": True}

    id: UUID
    target_id: UUID
    status: str
    triggered_by: Optional[str]
    started_at: Optional[datetime]
    completed_at: Optional[datetime]
    report: Optional[dict] = None
