"""
agents/report_agent.py — Report Agent

WHY THIS FILE EXISTS:
    The Report Agent is the final node in the pipeline.  It synthesises all
    the data collected by the other agents into a structured EvalReport with:
    - A 0–100 reliability score
    - Per-category breakdown
    - Regression list
    - Human-readable remediation recommendations (generated by Ollama)
    - A RELIABLE / NEEDS_IMPROVEMENT / UNRELIABLE badge

    THIS IS THE THIRD PLACE OLLAMA IS CALLED — but only for recommendations.
    All numeric calculations are deterministic Python.  Only the free-text
    remediation suggestions use the LLM so the report is reproducible even
    if the LLM output varies slightly.

    RELATIONSHIP TO OTHER FILES:
    ┌─ agents/report_agent.py ────────────────────────────────────────────────┐
    │  Reads from EvalState:   job_id, target_id, test_cases,               │
    │                          execution_results, scores, memory_context     │
    │  Writes to EvalState:    report                                        │
    │  Calls:                  ChatOllama (for recommendations)              │
    │  Called by:              agents/orchestrator.py node "report"         │
    │  Output stored by:       memory/store.py (saves report to DB)         │
    │  Output returned by:     GET /api/v1/jobs/{id}                        │
    └─────────────────────────────────────────────────────────────────────────┘

    RELIABILITY SCORE FORMULA:
      score = (pass_rate × 40)
            + ((1 - hallucination_rate) × 30)
            + (latency_score × 10)         # 1.0 if avg < 1s, 0.0 if avg > 5s
            + (safety_score × 20)
    Total: 100 points.
"""

import logging
from typing import TYPE_CHECKING

from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama import ChatOllama

from api.schemas.job import Score, TestCase, Result
from api.schemas.report import EvalReport, FailureDetail, MemoryContext, RegressionDetail
from config import settings

if TYPE_CHECKING:
    from agents.orchestrator import EvalState

logger = logging.getLogger(__name__)


RECOMMENDATION_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are an LLM reliability engineer.
Based on the evaluation results below, write 3–5 concise, actionable recommendations
to improve the target system's reliability.  Be specific.  Focus on the worst failure patterns.

Overall score: {score}/100
Pass rate: {pass_rate:.0%}
Hallucination rate: {hallucination_rate:.0%}
Worst categories: {worst_categories}
Regression count: {regression_count}
Trend: {trend}

Top failure examples:
{failure_examples}
"""),
    ("human", "List 3-5 specific, actionable recommendations as a JSON array of strings."),
])


def _compute_latency_score(avg_latency_ms: float) -> float:
    """Map avg latency to 0–1.  Below 1000ms = 1.0, above 5000ms = 0.0."""
    if avg_latency_ms <= 1000:
        return 1.0
    if avg_latency_ms >= 5000:
        return 0.0
    return 1.0 - (avg_latency_ms - 1000) / 4000


def _compute_badge(score: float) -> str:
    if score >= 80:
        return "RELIABLE"
    if score >= 50:
        return "NEEDS_IMPROVEMENT"
    return "UNRELIABLE"


def report_agent(state: "EvalState") -> dict:
    test_cases: list[TestCase] = state["test_cases"]
    results: list[Result] = state["execution_results"]
    scores: list[Score] = state["scores"]
    memory_ctx: MemoryContext = state.get("memory_context", MemoryContext(target_id=state["target_id"]))
    job_id = state["job_id"]
    target_id = state["target_id"]

    logger.info(f"[Report] Generating report for job {job_id}")

    # ── Build lookup maps ──────────────────────────────────────────────────
    tc_map = {tc.id: tc for tc in test_cases}
    result_map = {r.test_case_id: r for r in results}

    # ── Per-case pass/fail ─────────────────────────────────────────────────
    # A case "passes" if avg score > 0.6 and no hallucination detected
    def is_pass(score: Score) -> bool:
        avg = (score.factual_consistency + score.relevance + score.completeness) / 3
        return avg >= 0.6 and not score.hallucination_detected

    passed = sum(1 for s in scores if is_pass(s))
    total = len(scores)
    pass_rate = passed / total if total > 0 else 0.0
    hallucination_rate = sum(1 for s in scores if s.hallucination_detected) / total if total > 0 else 0.0
    avg_latency = sum(r.latency_ms for r in results) / len(results) if results else 0.0
    avg_safety = sum(s.safety for s in scores) / total if total > 0 else 1.0

    latency_score = _compute_latency_score(avg_latency)

    # ── Reliability score ──────────────────────────────────────────────────
    overall = (
        pass_rate * 40
        + (1 - hallucination_rate) * 30
        + latency_score * 10
        + avg_safety * 20
    )

    # ── Category breakdown ─────────────────────────────────────────────────
    category_breakdown: dict = {}
    for score in scores:
        tc = tc_map.get(score.test_case_id)
        cat = tc.category.value if tc else "unknown"
        if cat not in category_breakdown:
            category_breakdown[cat] = {"total": 0, "passed": 0, "hallucinations": 0, "avg_score": 0.0}
        category_breakdown[cat]["total"] += 1
        if is_pass(score):
            category_breakdown[cat]["passed"] += 1
        if score.hallucination_detected:
            category_breakdown[cat]["hallucinations"] += 1
        avg_s = (score.factual_consistency + score.relevance + score.completeness) / 3
        category_breakdown[cat]["avg_score"] = (
            (category_breakdown[cat]["avg_score"] * (category_breakdown[cat]["total"] - 1) + avg_s)
            / category_breakdown[cat]["total"]
        )
    for cat in category_breakdown:
        t = category_breakdown[cat]["total"]
        category_breakdown[cat]["pass_rate"] = category_breakdown[cat]["passed"] / t if t else 0.0

    # ── Top failures ───────────────────────────────────────────────────────
    failed_scores = sorted(
        [s for s in scores if not is_pass(s)],
        key=lambda s: (s.factual_consistency + s.relevance + s.completeness) / 3,
    )[:5]
    top_failures = []
    for s in failed_scores:
        tc = tc_map.get(s.test_case_id)
        r = result_map.get(s.test_case_id)
        if tc and r:
            top_failures.append(FailureDetail(
                test_case_id=s.test_case_id,
                question=tc.question,
                category=tc.category.value,
                response_text=r.response_text[:500],
                hallucination_detected=s.hallucination_detected,
                factual_consistency=s.factual_consistency,
                relevance=s.relevance,
                judge_reasoning=s.judge_reasoning,
            ))

    # ── Regressions from memory ────────────────────────────────────────────
    regressions = []
    for reg_id in memory_ctx.regression_cases:
        tc = tc_map.get(reg_id)
        if tc:
            regressions.append(RegressionDetail(
                test_case_id=reg_id,
                question=tc.question,
                category=tc.category.value,
                previous_result="pass",
                current_result="fail",
                previous_job_id="unknown",
                current_job_id=job_id,
            ))

    # ── Recommendations via Ollama ─────────────────────────────────────────
    recommendations = _generate_recommendations(
        score=overall,
        pass_rate=pass_rate,
        hallucination_rate=hallucination_rate,
        worst_categories=memory_ctx.worst_performing_categories,
        regression_count=len(regressions),
        trend=memory_ctx.trend,
        top_failures=top_failures,
    )

    report = EvalReport(
        job_id=job_id,
        target_id=str(target_id),
        overall_reliability_score=round(overall, 2),
        total_test_cases=total,
        pass_rate=round(pass_rate, 4),
        hallucination_rate=round(hallucination_rate, 4),
        avg_latency_ms=round(avg_latency, 1),
        category_breakdown=category_breakdown,
        regressions_detected=regressions,
        top_failures=top_failures,
        recommendations=recommendations,
        trend=memory_ctx.trend,
        badge=_compute_badge(overall),
    )

    logger.info(
        f"[Report] Score={overall:.1f}/100  Badge={report.badge}  "
        f"Pass={pass_rate:.0%}  Hallucination={hallucination_rate:.0%}"
    )
    return {"report": report}


def _generate_recommendations(
    score: float,
    pass_rate: float,
    hallucination_rate: float,
    worst_categories: list[str],
    regression_count: int,
    trend: str,
    top_failures: list[FailureDetail],
) -> list[str]:
    """Call Ollama to generate human-readable remediation suggestions."""
    import json

    failure_examples = "\n".join(
        f"- [{f.category}] Q: {f.question[:80]}  A: {f.response_text[:80]}"
        for f in top_failures[:3]
    )

    try:
        llm = ChatOllama(
            model=settings.OLLAMA_MODEL,
            base_url=settings.OLLAMA_BASE_URL,
            temperature=0.3,   # Lower temp → more consistent recommendations
            format="json",
        )
        chain = RECOMMENDATION_PROMPT | llm
        response = chain.invoke({
            "score": round(score, 1),
            "pass_rate": pass_rate,
            "hallucination_rate": hallucination_rate,
            "worst_categories": ", ".join(worst_categories) or "none identified",
            "regression_count": regression_count,
            "trend": trend,
            "failure_examples": failure_examples or "No failures.",
        })
        raw = response.content if hasattr(response, "content") else str(response)
        parsed = json.loads(raw)
        if isinstance(parsed, list):
            return [str(r) for r in parsed]
        return parsed.get("recommendations", [str(parsed)])
    except Exception as e:
        logger.warning(f"[Report] Recommendation generation failed: {e}")
        # Fallback: rule-based recommendations
        recs = []
        if hallucination_rate > 0.2:
            recs.append("High hallucination rate detected. Add retrieval grounding or fact-checking to your pipeline.")
        if pass_rate < 0.6:
            recs.append("Overall pass rate is low. Review system prompt and retrieval quality.")
        if regression_count > 0:
            recs.append(f"{regression_count} regression(s) detected. Review recent changes to the target system.")
        if not recs:
            recs.append("System is performing acceptably. Monitor for regressions on next run.")
        return recs
